development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7e523fdb2803ce4c9196c1062539bfa7@soapfish.redistogo.com:11165/
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: todo_production
